from typing import Any

import numpy as np


class Quadtree:
    def __init__(self, width: int, height: int, max_depth: int) -> None: ...
    def cleanup(self) -> None: ...
    def insert(self, id: int, x1: float, y1: float, x2: float, y2: float) -> int: ...
    def query(self, x1:float,y1:float,x2:float,y2:float,omit_element:int) -> np.ndarray: ...
    def remove(self, element: int) -> None: ...
